### get all users
GET http://localhost:3000/api/users

### get user by id
GET http://localhost:3000/api/users/698fc887633cc499a80d94d2

### create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Shaked",
  "email": "shaked@example.com",
  "password": "password123"
}


### update user
PUT http://localhost:3000/api/users/698fc782633cc499a80d94c3
Content-Type: application/json

{
  "name": "Shaked Updated",
  "email": "shaked.updated@example.com",
  "password": "newpassword123"
}

### delete user
DELETE http://localhost:3000/api/users/698fc782633cc499a80d94c3




### get all recipes
GET http://localhost:3000/api/recipes

### get recipe by id
GET http://localhost:3000/api/recipes/6990f7f6b3ed23b4f5d58571

### get recipe by user id
GET http://localhost:3000/api/recipes/user/698fc782633cc499a80d94c3

### create recipe
POST http://localhost:3000/api/recipes
Content-Type: application/json

{
  "title": "Shaked's Recipe",
  "description": "A delicious recipe created by Shaked",
  "image": "https://example.com/image.jpg",
  "prepTime": 15,
  "cookTime": 30,
  "servings": 4,
  "ingredients": [
    {
      "amount": "2 cups",
      "name": "flour"
    },
    {
      "amount": "1 cup",
      "name": "sugar"
    }
  ],
  "instructions": [
    "Mix ingredients together.",
    "Bake in oven for 30 minutes."
  ],
  "userId": "698fc782633cc499a80d94c3"
}


### update recipe
PUT http://localhost:3000/api/recipes/6990f7f6b3ed23b4f5d58571
Content-Type: application/json

{
  "title": "Shaked's Updated Recipe",
  "description": "An updated delicious recipe created by Shaked",
  "image": "https://example.com/updated-image.jpg",
  "prepTime": 20,
  "cookTime": 35,
  "servings": 6,
  "ingredients": [
    {
      "amount": "2.5 cups",
      "name": "flour"
    },
    {
      "amount": "1.5 cups",
      "name": "sugar"
    }
  ],
  "instructions": [
    "Mix ingredients together.",
    "Bake in oven for 35 minutes."
  ]
}

### delete recipe
DELETE http://localhost:3000/api/recipes/6990f7f6b3ed23b4f5d58571





### get comment by id
GET http://localhost:3000/api/comments/6990fad3d9952528e0d3e4d9

### get comments by recipe id
GET http://localhost:3000/api/comments/recipe/6990f7f6b3ed23b4f5d58571

### create comment
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "text": "This is a great recipe!",
  "userId": "698fc782633cc499a80d94c3",
  "recipeId": "6990f7f6b3ed23b4f5d58571"
}


### update comment
PUT http://localhost:3000/api/comments/6990fad3d9952528e0d3e4d9
Content-Type: application/json

{
  "text": "This is an updated great recipe!",
  "userId": "698fc782633cc499a80d94c3",
  "recipeId": "6990f7f6b3ed23b4f5d58571"
}

### delete comment
DELETE http://localhost:3000/api/comments/6990fb06d9952528e0d3e4e2





### create like
POST http://localhost:3000/api/likes
Content-Type: application/json

{
  "userId": "698fc782633cc499a80d94c4",
  "recipeId": "6990f7f6b3ed23b4f5d58572"
}

### get likes count on recipe
GET http://localhost:3000/api/likes/recipe/6990f7f6b3ed23b4f5d58572

### get likes by user id
GET http://localhost:3000/api/likes/user/698fc782633cc499a80d94c4

### check if user liked recipe
GET http://localhost:3000/api/likes/check/698fc782633cc499a80d94c3/6990f7f6b3ed23b4f5d58572

### delete like
DELETE http://localhost:3000/api/likes
Content-Type: application/json

{
  "userId": "698fc782633cc499a80d94c4",
  "recipeId": "6990f7f6b3ed23b4f5d58572"
}