import { Request, Response } from "express";
import { generateRecipesByChatGPT } from "../services/chatgptService";

/**
 * Generate recipes based on user input in Hebrew or English
 * Returns 1-3 recipes generated by ChatGPT
 */
export const suggestRecipes = async (
  req: Request,
  res: Response,
): Promise<void> => {
  try {
    const { input } = req.body;

    if (!input || typeof input !== "string") {
      res.status(400).json({ error: "Please provide a valid text input" });
      return;
    }

    const recipes = await generateRecipesByChatGPT(input);

    if (recipes.length === 0) {
      res.status(400).json({
        error: "Could not generate recipes from the provided input",
      });
      return;
    }

    res.status(200).json({
      input,
      count: recipes.length,
      recipes,
    });
  } catch (error: any) {
    console.error("Error in suggestRecipes:", error);
    res.status(500).json({
      error: error.message || "Failed to generate recipes",
    });
  }
};
